### ISSUE TITLE
Add Glyph code in the list of icons

### ISSUE THREAD

**Issue by binamracode** [microsoft/fluentui-system-icons#141]
I did not find the list of glyph code where I can search icons.
Can you please add new column in this [page](https://github.com/microsoft/fluentui-system-icons/blob/master/icons.md) with glyph code or Unicode Point? Searching in character map is hard.

**Comment by aakash1313** [comment]
@binamracode , due to the way we generate icons the glyph code might change if we add or drop an icon in a particular release. Therefore it won't be possible right now to add the column to depict the code currently. We are looking into possible solutions for making the codepoints stable going forward and shall update the icons page once we do that. But for the time feel free to take a look at these files and see it solves your issue :

https://github.com/microsoft/fluentui-system-icons/blob/master/fonts/FluentSystemIcons-Regular.json

https://github.com/microsoft/fluentui-system-icons/blob/master/fonts/FluentSystemIcons-Filled.json

**Comment by Leon99** [comment]
@aakash1313 any chance you could update the json files to have all the icons listed in https://github.com/microsoft/fluentui-system-icons/blob/main/icons_regular.md?
