### ISSUE TITLE
Question: Why does the 'Collections' icon have a plus symbol?

### ISSUE THREAD

**Issue by cervonwong** [microsoft/fluentui-system-icons#254]
Collections 24 Regular: ![](https://raw.githubusercontent.com/microsoft/fluentui-system-icons/40d00265b6e84f090eeee7c49b2bf7b3c92c02aa/assets/Collections/SVG/ic_fluent_collections_24_regular.svg)

My understanding is that a collection is a group of items. What would this icon be used for? Why is there a plus icon in the Collections icon? I'm considering using this icon to represent a deck of cards for my app, would it be appropriate?

For comparison, here is Collections Add 24 Regular : ![](https://raw.githubusercontent.com/microsoft/fluentui-system-icons/40d00265b6e84f090eeee7c49b2bf7b3c92c02aa/assets/Collections%20Add/SVG/ic_fluent_collections_add_24_regular.svg)

**Comment by mdtauk** [comment]
Collections you add to I would guess.

**Comment by jasoncuster** [comment]
Hi @cervonwong! This is used for Collections on Edge - hence the very specific name - with the second one being  'adding to that collection'. Admittedly is a little confusing considering the double pluses...haha.

One thing we've set out for the set is to keep things abstract enough that they could be used in multiple scenarios - since we don't have a card stack and if you feel that works, use it!

Also thanks for using the set!
