### ISSUE TITLE
Icon Submission: Slide Add

### ISSUE THREAD

**Issue by danielsoliman** [microsoft/fluentui-system-icons#356]
Slide Add in the following sizes: 16px, 20px, 28px, 32px, 48px. All Regular and Filled. See Figma here https://www.figma.com/file/8M8JTEaXot1DTRedUmnpaN/Fluent-Icon-Submission%3A-Slide-Add?node-id=0%3A1

**Comment by jasoncuster** [comment]
Thanks @danielsoliman - these look great! There were a few tweaks that needed to be made, but all small things
![image](https://user-images.githubusercontent.com/20647412/141204431-9d384ddf-ee41-4a30-b891-e58d1b152ebb.png)

For the 16px version, the rectangle was slightly off pixel and smaller than our keyline, so was tweaked. Also we adjusted it to be a bit more balanced in the space - something that we do with 16px modifier versions only, so I've noted that to be added t to the updated guidelines (coming next month!).

There were a few filled that were missing the stroke (20 & 28) - something that happens when editing the shape (subtract in this case). That's something we'll be fixing with the updated guidelines & creation tools.

Last small issue was the 32px modifier - it looks like it might have been center in the space, which from my designer side I love, but we try to keep the 1.5 strokes tethered to hard edge of a pixel. Another thing that we'll be adding to updated guidelines & creation tools.

All and all great work - thank you for contributing. We'll be adding these to our files when the current sprint ends (Nov 19th).

**Comment by danielsoliman** [comment]
Am I making these tweaks or someone else?

**Comment by jasoncuster** [comment]
Let's paper, rock, scissors for it...haha. We'll make these update before adding to the library. Thanks again for doing these!
