### ISSUE TITLE
LTR and RTL icon were built into same imageset in iOS

### ISSUE THREAD

**Issue by GrayLeee** [microsoft/fluentui-system-icons#367]
icon with "LTR" and "RTL" were built into same imageset like below, while icon with "left" and "right" are in standalone imageset, is this by design?

![image](https://user-images.githubusercontent.com/22672403/143385776-5bdf6464-0da9-4f08-bc8b-5d4fdbc971ad.png)

![image](https://user-images.githubusercontent.com/22672403/143386153-14d1d8f4-6920-4859-b420-2d62b3a40516.png)

**Comment by spencer-nelson** [comment]
LTR/RTL are intended for icons that have language/locale information built into them, while 'normal' right and left directions, mostly for arrows, are left non-localized because they don't inherently include information which should be strictly relevant to the directionality of the language used for the UI.

If you have/see need for a particular icon to always have its direction treated with respect to language, please feel welcome to propose a fix.
