### ISSUE TITLE
Icons missing popular brands

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fluentui-system-icons#447]
Creating issue here with ref to https://github.com/microsoft/fast-blazor/issues/186

The icons seem to be missing the popular brands that are used often such as , 
- GitHub, Stripe, AWS, Microsoft, Azure etc...
- OS Icons Windows, Linus, macOS
- Technology icons
-etc...

**Comment by spencer-nelson** [comment]
Hello, thanks for your request. Due to licensing restrictions we can't include branded icons in this repository at this time. If some of the "Technology icons" you mention are generic/open like [Headset](https://github.com/microsoft/fluentui-system-icons/blob/master/assets/Headset/SVG/ic_fluent_headset_24_regular.svg) we can look further into it, though.
